### PR TITLE
Add compatibility with Symfony 3

### PR DESCRIPTION
**Pull request by borisceranic**
This PR adds Symfony 3 compatibility to this handy bundle.

Unit tests pass using both ~2.6 (v2.8.6) and ~3.0 (v3.0.6) symfony branches.

Could you also please tag the new version as v1.1.0 or v2.0.0 and make it available on the Packagist?

### CODE REVIEW

**Comment by mremi** [comment]
Hi @borisceranic ,

The Symfony branch 2.6 is not maintained anymore, so I think we need to require ~2.8|~3.0. Maybe it would be interesting to add in the README.md that the tags ~1.0 should be used to work with Symfony < 2.6.
Can you update your changes and think to squash your commits please?

Thx for your time!

**Comment by borisceranic** [comment]
Hey @mremi,

I added ~2.6 requirement because it is the lowest Symfony version, which uses new `factory` service configuration option. Though, I completely agree that the library should depend on the LTS version instead.

**Comment by borisceranic** [comment]
Please take a look at the squashed commit I just pushed. I hope it is satisfactory for merging.

**Comment by mremi** [comment]
Thanks @borisceranic ! I just created a tag v1.1.0. See you!

**Comment by borisceranic** [comment]
You are welcome! See you, indeed :)

By the way, I think I made an omission in the README instructions, saying that =< 2.7 compatibility is achieved using ~1.0 version specifier, because this version specifier is equal to *1.x.x*.

The thing is, Composer will correctly resolve which exact version of a bundle to install, regardless of the version specifier, because it will *have to* use lower versions of the bundle (1.0.x) if SF version is lower than 2.8, because no other version is compatible with it.

My point is, you can safely remove that info about older versions of Symfony from README, if you wish :)

Best regards!

**Comment by mremi** [comment]
My bad, you're right, this is my fault :) thank you

**Pull request merged**
